# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-01 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_model',
            name='module_type',
            field=models.CharField(default='', max_length=20, verbose_name='所属板块'),
        ),
    ]
