# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-21 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200413_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article_like_comment',
            fields=[
                ('article_id', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='文章id')),
                ('like_count', models.IntegerField(verbose_name='点赞数')),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '点赞评论总数',
                'verbose_name_plural': '点赞评论总数',
                'db_table': 't_like_count',
            },
        ),
        migrations.CreateModel(
            name='User_like_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=16, verbose_name='文章id')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('status', models.BooleanField(verbose_name='点赞状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户点赞表',
                'verbose_name_plural': '用户点赞表',
                'db_table': 't_user_like_article',
            },
        ),
    ]
