# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-05 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_model_module_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_model',
            name='author',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article_model',
            name='content',
            field=models.CharField(blank=True, default='', max_length=4000, verbose_name='正文'),
        ),
    ]
