# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-24 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_like_comment_user_like_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_like_comment',
            name='comment_count',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
        migrations.AlterField(
            model_name='article_like_comment',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
    ]
