# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-15 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200424_0944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article_model',
        ),
        migrations.AlterField(
            model_name='article_info_model',
            name='next',
            field=models.CharField(blank=True, default='', max_length=36, verbose_name='下一篇'),
        ),
        migrations.AlterField(
            model_name='article_info_model',
            name='next_url',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='下一url'),
        ),
    ]
