# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-15 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200715_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_info_model',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info', to='article.Article_level_model'),
        ),
    ]
