# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-27 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200227_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund_payment_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=1)),
                ('remarks', models.CharField(blank=True, default='', max_length=50)),
                ('order_code', models.CharField(db_index=True, max_length=32, verbose_name='订单号')),
                ('fund_code', models.CharField(db_index=True, max_length=20, verbose_name='基金编号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='单价')),
                ('total', models.IntegerField(default=1, verbose_name='数量')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总金额')),
                ('status', models.SmallIntegerField(default=1, verbose_name='订单状态')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User_profile_model')),
            ],
            options={
                'verbose_name': '订单管理表',
                'verbose_name_plural': '订单管理表',
                'db_table': 't_fund_payment',
            },
        ),
    ]
