# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-06 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund_payment_model',
            options={'ordering': ['status', '-create_time'], 'verbose_name': '订单管理表', 'verbose_name_plural': '订单管理表'},
        ),
        migrations.AlterField(
            model_name='fund_payment_model',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fund_payment_model',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
