# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200307_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_payment_model',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fund_payment_model',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
