# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-13 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=50)),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(db_index=True, max_length=25, verbose_name='手机号码')),
                ('gender', models.CharField(blank=True, default=None, max_length=3, verbose_name='性别')),
                ('nickname', models.CharField(blank=True, default='', max_length=16, verbose_name='昵称')),
                ('age', models.IntegerField(blank=True, default=0, verbose_name='年龄')),
                ('ability', models.IntegerField(blank=True, default=0, verbose_name='风险能力')),
                ('preference', models.IntegerField(blank=True, default=0, verbose_name='风险偏好')),
                ('uid', models.CharField(max_length=32, verbose_name='第三方id')),
                ('is_active', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
                'db_table': 'user_profile',
                'ordering': ('-id',),
            },
        ),
    ]
