# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-13 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_model',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='第三方id'),
        ),
    ]
