# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-27 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200213_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_model',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='性别'),
        ),
    ]
