# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-07 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200307_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_model',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='update_time',
            field=models.DateField(auto_now=True),
        ),
    ]
