# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-24 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200307_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='user_img',
            field=models.CharField(default='userImg/1.jpg', max_length=32, verbose_name='用户头像'),
        ),
    ]
