# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-24 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_profile_model_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_model',
            name='live_flag',
            field=models.BooleanField(default=True, verbose_name='存活标记'),
        ),
        migrations.AlterField(
            model_name='user_profile_model',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
    ]
