# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-24 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200825_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_model',
            name='live_flag',
            field=models.SmallIntegerField(default=1, verbose_name='存活状态'),
        ),
    ]
