# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-04 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_comment_model',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='post.Post_bar_model'),
        ),
        migrations.AlterField(
            model_name='post_title_model',
            name='b_id',
            field=models.IntegerField(verbose_name='贴吧id'),
        ),
        migrations.AlterField(
            model_name='post_title_model',
            name='theme',
            field=models.CharField(db_index=True, max_length=50, verbose_name='主题'),
        ),
    ]
