# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_bar_model',
            options={'ordering': ['-t_sort', '-sort'], 'verbose_name': '基金吧表', 'verbose_name_plural': '基金吧表'},
        ),
        migrations.RenameField(
            model_name='post_comment_model',
            old_name='theme_id',
            new_name='theme_obj',
        ),
        migrations.RemoveField(
            model_name='post_bar_model',
            name='b_id',
        ),
        migrations.RemoveField(
            model_name='post_bar_model',
            name='id',
        ),
        migrations.RemoveField(
            model_name='post_title_model',
            name='bar_id',
        ),
        migrations.AddField(
            model_name='post_bar_model',
            name='bid',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='基金吧id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post_title_model',
            name='bar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barinfo', to='post.Post_bar_model'),
        ),
    ]
