# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-16 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_bar_model',
            name='b_code',
            field=models.CharField(default='gb100042', editable=False, max_length=20, unique=True, verbose_name='基金吧编号'),
        ),
        migrations.AlterField(
            model_name='post_bar_model',
            name='create_user',
            field=models.CharField(editable=False, max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='post_bar_model',
            name='post_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='帖子数量'),
        ),
        migrations.AlterField(
            model_name='post_bar_model',
            name='update_user',
            field=models.CharField(default='', editable=False, max_length=32, verbose_name='修改人'),
        ),
    ]
