# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-17 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200816_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_bar_model',
            name='b_code',
            field=models.CharField(blank=True, help_text='通常为基金编号，不可重复，默认不写自动生成。', max_length=20, unique=True, verbose_name='基金吧编号'),
        ),
        migrations.AlterField(
            model_name='post_bar_model',
            name='url',
            field=models.CharField(editable=False, max_length=50, verbose_name='贴吧路径'),
        ),
        migrations.AlterField(
            model_name='post_title_model',
            name='b_id',
            field=models.CharField(max_length=20, verbose_name='贴吧id'),
        ),
    ]
