# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-23 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200821_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_title_model',
            options={'ordering': ['-t_sort', '-update_time'], 'verbose_name': '贴吧标题表', 'verbose_name_plural': '贴吧标题表'},
        ),
        migrations.RenameField(
            model_name='post_comment_model',
            old_name='reply_count',
            new_name='revert_count',
        ),
        migrations.RenameField(
            model_name='post_comment_model',
            old_name='reply_id',
            new_name='revert_to',
        ),
        migrations.RemoveField(
            model_name='post_comment_model',
            name='theme_obj',
        ),
        migrations.AddField(
            model_name='post_comment_model',
            name='theme_id',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='帖子/主题id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post_bar_model',
            name='bid',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='基金吧id'),
        ),
        migrations.AlterField(
            model_name='post_comment_model',
            name='content',
            field=models.CharField(max_length=350, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='post_title_model',
            name='comment_count',
            field=models.IntegerField(default=0, editable=False, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='post_title_model',
            name='t_content',
            field=models.CharField(max_length=150, verbose_name='主题内容'),
        ),
        migrations.AlterField(
            model_name='post_title_model',
            name='tid',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='唯一id'),
        ),
        migrations.AlterField(
            model_name='post_title_model',
            name='url',
            field=models.CharField(editable=False, max_length=50, verbose_name='路径'),
        ),
    ]
