# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200804_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_bar_model',
            options={'ordering': ['t_sort', 'sort'], 'verbose_name': '基金吧表', 'verbose_name_plural': '基金吧表'},
        ),
        migrations.AlterField(
            model_name='post_comment_model',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid', to='post.Post_title_model'),
        ),
    ]
