# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-17 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200817_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_title_model',
            name='b_id',
            field=models.CharField(db_index=True, max_length=20, verbose_name='贴吧id'),
        ),
        migrations.AlterField(
            model_name='post_title_model',
            name='has_image',
            field=models.BooleanField(default=False, verbose_name='图片贴'),
        ),
    ]
