# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-24 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200824_0631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_comment_model',
            options={'ordering': ['parent_id', 'sort'], 'verbose_name': '贴吧评论表', 'verbose_name_plural': '贴吧评论表'},
        ),
    ]
