# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-05 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund_company',
            fields=[
                ('c_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='公司id')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=1)),
                ('remarks', models.CharField(blank=True, default='', max_length=50)),
                ('c_name', models.CharField(max_length=60, verbose_name='名称')),
                ('sort', models.IntegerField(default=None, verbose_name='排序')),
                ('create_user', models.CharField(blank=True, default=None, max_length=32, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '基金公司表',
                'verbose_name_plural': '基金公司表',
                'db_table': 't_fund_company',
            },
        ),
        migrations.CreateModel(
            name='Fund_filter_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=1)),
                ('remarks', models.CharField(blank=True, default='', max_length=50)),
                ('f_code', models.CharField(max_length=20, verbose_name='编号')),
                ('f_name', models.CharField(db_index=True, max_length=50, verbose_name='基金名称')),
                ('company_id', models.IntegerField(db_index=True, verbose_name='公司id')),
                ('is_oc', models.IntegerField(default=1, verbose_name='is_开闭')),
                ('is_eq', models.IntegerField(default=0, verbose_name='is_EQ')),
                ('f_type_id', models.IntegerField(default=None, verbose_name='基金类型id')),
                ('five_year_level', models.FloatField(default=0, verbose_name='五年评级')),
                ('three_year_level', models.FloatField(default=0, verbose_name='三年评级')),
                ('unit_price', models.CharField(default=None, max_length=30, verbose_name='单位净值')),
                ('day_change', models.DecimalField(decimal_places=4, default=None, max_digits=5, verbose_name='日变动')),
                ('interest', models.DecimalField(decimal_places=2, default=None, max_digits=6, verbose_name='今年来回报')),
            ],
            options={
                'verbose_name': '基金筛选表',
                'verbose_name_plural': '基金筛选表',
                'db_table': 't_fund_filter',
            },
        ),
        migrations.CreateModel(
            name='Fund_type',
            fields=[
                ('t_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='类型id')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=1)),
                ('remarks', models.CharField(blank=True, default='', max_length=50)),
                ('type_name', models.CharField(max_length=128, verbose_name='基金类型')),
                ('sort', models.IntegerField(default=None, verbose_name='排序')),
            ],
            options={
                'verbose_name': '基金类型表',
                'verbose_name_plural': '基金类型表',
                'db_table': 't_fund_type',
            },
        ),
    ]
