# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-27 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_auto_20200212_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_filter_model',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=7, verbose_name='单位净值'),
        ),
    ]
