# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-26 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_auto_20200307_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund_info_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=1)),
                ('remarks', models.CharField(blank=True, default='', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
