# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-08-15 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_fund_info_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_filter_model',
            name='f_code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='编号'),
        ),
    ]
