-- ----------------------------
-- Table structure for t_fund_filter
-- ----------------------------

INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (1, '2020-02-12', '2020-02-12', 1, '', '股票型', 10);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (2, '2020-02-12', '2020-02-12', 1, '', '行业股票-医药', 20);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (3, '2020-02-12', '2020-02-12', 1, '', '科技、传媒及通讯', 30);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (4, '2020-02-12', '2020-02-12', 1, '', '沪港深股票', 40);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (5, '2020-02-12', '2020-02-12', 1, '', '香港股票', 50);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (6, '2020-02-12', '2020-02-12', 1, '', '激进配置', 60);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (7, '2020-02-12', '2020-02-12', 1, '', '灵活配置', 70);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (8, '2020-02-12', '2020-02-12', 1, '', '标准混合', 80);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (9, '2020-02-12', '2020-02-12', 1, '', '保守混合', 90);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (10, '2020-02-12', '2020-02-12', 1, '', '沪港深混合', 100);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (11, '2020-02-12', '2020-02-12', 1, '', '可转债', 110);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (12, '2020-02-12', '2020-02-12', 1, '', '激进债券', 120);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (13, '2020-02-12', '2020-02-12', 1, '', '普通债券', 130);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (14, '2020-02-12', '2020-02-12', 1, '', '纯债基金', 140);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (15, '2020-02-12', '2020-02-12', 1, '', '短债基金', 150);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (16, '2020-02-12', '2020-02-12', 1, '', '货币基金', 160);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (17, '2020-02-12', '2020-02-12', 1, '', '市场中性', 170);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (18, '2020-02-12', '2020-02-12', 1, '', '商品', 180);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (19, '2020-02-12', '2020-02-12', 1, '', '保本基金', 190);
INSERT INTO `fund_web`.`t_fund_type`(`t_id`, `create_time`, `update_time`, `is_active`, `remarks`, `type_name`, `sort`) VALUES (20, '2020-02-12', '2020-02-12', 1, '', '其他', 20);

-- ----------------------------
-- Table structure for t_sync_code
-- ----------------------------

INSERT INTO `fund_web`.`t_sync_code`(`id`, `module`, `prefix`, `serial_num`) VALUES (1, 'ali_pay', 'rxfd', 100035);

-- ----------------------------
-- Table structure for system_dict
-- ----------------------------

INSERT INTO `fund_web`.`system_dict`(`id`, `create_time`, `update_time`, `is_active`, `remarks`, `type`, `valid`, `value`, `sort`, `create_user`) VALUES (2, '2020-01-28', '2020-01-28', 1, '', 'oc_sel', 1, '封闭式', 10, '');
INSERT INTO `fund_web`.`system_dict`(`id`, `create_time`, `update_time`, `is_active`, `remarks`, `type`, `valid`, `value`, `sort`, `create_user`) VALUES (3, '2020-01-29', '2020-01-29', 1, '', 'oc_sel', 2, '开放式', 20, '');
INSERT INTO `fund_web`.`system_dict`(`id`, `create_time`, `update_time`, `is_active`, `remarks`, `type`, `valid`, `value`, `sort`, `create_user`) VALUES (4, '2020-01-29', '2020-01-29', 1, '', 'eq_sel', 1, 'ETF', 10, '');
INSERT INTO `fund_web`.`system_dict`(`id`, `create_time`, `update_time`, `is_active`, `remarks`, `type`, `valid`, `value`, `sort`, `create_user`) VALUES (5, '2020-01-29', '2020-01-29', 1, '', 'eq_sel', 2, 'QDII', 20, '');

-- ----------------------------
-- Table structure for t_article
-- ----------------------------

INSERT INTO `fund_web`.`t_article`(`id`, `create_time`, `update_time`, `is_active`, `remarks`, `title`, `url`, `article_type`, `article_id`, `parent_id`, `author`, `content`, `sort`, `module_type`) VALUES (1, '2020-02-01', '2020-02-03', 1, '', '新基金观察', '/article/survey', 'survey', 'ais', '0', '', '', 10, 'art_info');
INSERT INTO `fund_web`.`t_article`(`id`, `create_time`, `update_time`, `is_active`, `remarks`, `title`, `url`, `article_type`, `article_id`, `parent_id`, `author`, `content`, `sort`, `module_type`) VALUES (2, '2020-02-01', '2020-02-03', 1, '', '新基金观察（201910）： 定开债基成发行热点 权益类 基金 爆款频现', '/article/survey/ais1', 'survey', 'ais1', 'ais', '吴雪艳', '<div class=\"ar_content clearfix\"><p style=\"text-indent: 2em; line-height: 20pt;\"><font face=\"宋体\"><span style=\"font-size: 14.6667px;\">产品动态回顾</span></font></p> <p style=\"text-indent: 2em; line-height: 20pt;\"><font face=\"宋体\"><span style=\"font-size: 14.6667px;\">随着下半年市场震荡下行，投资者避险情绪升温。在货币市场基金监管要求日趋严格的背景下，债券型基金承接了低风险投资的溢出需求。而定开债基作为债券型基金的一种，因其规模稳定、可配置低流动性品种获取更高收益的特性迅速走红。叠加摊余成本法的推出，定开债基的净值不再随着二级市场的涨跌而大幅波动，长期稳定的收益使得该类产品受到众多个人和机构投资者的青睐。在需求上升的同时，基金公司也纷纷抢滩布局旗下的定开债基，以期通过该类基金助力公司固收产品的规模增长。目前来看，超长期限定开债基是基金公司的重点发行对象。不同于此前市场上较为常见的三年内短期定开债基，5年以上的超长期限定开债基正在集中上报，其中浦银安盛旗下的定开债基期限长达九年半。超长期限定开债基一般都是机构定制化产品：一方面，机构资金的长期配置需求高，超长期限定开债基的持有周期刚好与其匹配；另一方面，公募基金自带节税属性，与债基的长期合作可为机构带来一定的税务优惠。</span></font></p> <p style=\"text-indent: 2em; line-height: 20pt;\"><font face=\"宋体\"><span style=\"font-size: 14.6667px;\">市场概述</span></font></p> <p style=\"text-indent: 2em; line-height: 20pt;\"><font face=\"宋体\"><span style=\"font-size: 14.6667px;\">受十一假期影响，10月基金发行市场明显遇冷。截至2019年10月31日，当月新成立的基金共40只，合计募得809.63亿元资金。与9月发行<a href=\"../fundmanagers/ManagerHistory.aspx?ManagerId=2108507\" target=\"_blank\">高峰</a>相比，10月新基金数量及规模均出现了大幅下滑。然而，10月新成立基金的平均发行规模为20.24亿元，较上月环比增长39%，创下年内最高水平。由此看来，投资者申购新发基金的意愿仍较为强烈，数量及规模的下降主要是受到月初长假的拖累。</span></font></p> <p style=\"text-indent: 2em; line-height: 20pt;\"><font face=\"宋体\"><span style=\"font-size: 14.6667px;\">从运作方式来看，开放式基金募集规模在10月大幅下跌，当月获得资金（371.51亿元）仅为前月（1249.01亿元）的三成不到，其中ETF基金和其他开放式基金分别下降了457.67亿元和419.81亿元。相比之下，封闭式基金吸金能力在10月显著增强，合计募得438.11亿元资金，占总募集规模的比例由上月的27.07%上升至当月的54.11%。值得注意的是，10月成立的9只封闭式基金均为定期开放债券型基金，平均规模达到48.67亿元，远高于ETF基金15.70亿元和其他开放式基金10.89亿元的平均规模水平。</span></font><font face=\"宋体\"><span style=\"font-size: 14.6667px;\" /></font></p> <p>&nbsp;</p></div>', 10, 'art_info');
INSERT INTO `fund_web`.`t_article`(`id`, `create_time`, `update_time`, `is_active`, `remarks`, `title`, `url`, `article_type`, `article_id`, `parent_id`, `author`, `content`, `sort`, `module_type`) VALUES (3, '2020-02-01', '2020-02-03', 1, '', '新基金观察（201911）：ETF、定开债基密集发行 11月新基金规模再创新高', '/article/survey/ais2', 'survey', 'ais2', 'ais', '吴雪艳', '<p>产品动态回顾</p> <p>今年以来，投资者偏好逐渐向被动投资转变，叠加交易所降低ETF成本、提高交易效率等利好因素，多家基金公司纷纷布局旗下的ETF，该类产品的创新也层出不穷。从7月成立的科技主题类ETF，到9月成立的首批央企创新ETF，再到11月成立的助力国企一带一路ETF，创新产品不断进入新基金市场，在首次募集中的表现十分可观。然而，在近日监管层对规范ETF超额换购作出窗口指导之后，行业中陆续出现上市公司股东弃购ETF份额的现象。鉴于不少基金公司借助股份换购来做大首次发行的基金规模，这一调整或对日后新成立的权益ETF产品规模产生一定影响。</p> <p>年内另一个持续受到热捧的产品为中长期定开债基。在当前资产荒、利率低的大背景下，银行、保险等机构投资者对此类基金的需求旺盛，愿意大量买入并长期持有。为了吸引资金投入扩大公司规模，基金公司一直积极布局该类产品。值得注意的是，尽管该产品当前仍在密集发行，长期来看，定开债基未来的发展或将减速。一方面，此类产品多依赖机构定制，当机构需求趋于饱和时，可流向产品的资金将会逐渐减少;另一方面，监管层已对摊余成本法定开债基的审批节奏作出明确控制，产品发行速度会日趋下降。</p> <p>市场概述<br /> &nbsp; &nbsp;在基金分类审批改革和行情回暖的双重推动下，11月基金发行市场异常火热。截至2019年11月30日，当月新成立的基金共102只，合计募得2309.20亿元资金，创下年内月度募集规模的新高，也是2015年7月牛市高点后新成立基金单月募资规模的最好成绩。在单只基金方面，11月的平均募集规模为22.63亿元，亦超过10月20.24亿元的高点达到年内峰值。由此可见，基金公司和投资者在11月均积极参与基金发行市场：一方面，基金公司试图借助新发基金推动年末公司产品规模;而另一方面，投资者对申购新基金的热情也在持续上涨。</p> <p>从运作方式来看，开放式基金在11月吸金能力大幅回升，合计募得1116.79亿元资金，较10月环比增长200.6%，仅次于年内9月峰值。其中，ETF基金和其他开放式基金分别较前月上涨了285.43亿元和459.84亿元。封闭式基金在当月募得1192.41亿元资金，占总募集规模的51.64%。封闭式基金强势的吸金能力归功于持续走俏的定开债基。11月新成立的20只封闭式基金全部为定开债基，期限以39个月(6只)和3个月(7只)居多。</p> <p>从基金结构来看，尽管混合型基金和股票型基金的募集规模在当月均出现较大的提升，11月的新基金市场依然由债券型基金主导。具体而言，11月共计成立50只债券型基金，募资规模达到1576.72亿元，分别占总成立基金数量和规模的49%和68%。值得注意的是，除频繁出现爆款基金的定开债基外，11月成立的海富通上证5年期地方政府债ETF的首募规模也突破百亿大关(109.78亿元)，刷新了债券ETF领域的新发记录。混合型基金规模可圈可点，11月新成立产品27只，合计募集资金398.91亿元，较上月环比增长194%。其中11月5日成立的汇添富稳健增长混合首募规模达到130.87亿元，是年内募集规模最大的混合型基金。股票型基金在11月募得资金331.47亿元，环比增长176%，成为年内月度新发规模次高。当月新成立的24只股票型基金全部为被动型基金，其中ETF及其联接基金有21只，指数基金有3只，表明被动权益投资愈发受到投资者青睐。此外，11月还新成立一只QDII 基金&mdash;&mdash;华宝致远混合，首次募集规模达到20.89亿元。</p>', 20, 'art_info');
INSERT INTO `fund_web`.`t_article`(`id`, `create_time`, `update_time`, `is_active`, `remarks`, `title`, `url`, `article_type`, `article_id`, `parent_id`, `author`, `content`, `sort`, `module_type`) VALUES (4, '2020-02-02', '2020-02-02', 1, '', '行业动态', '/article/indu', 'indu', 'aii', '0', '', '', 20, 'art_info');
INSERT INTO `fund_web`.`t_article`(`id`, `create_time`, `update_time`, `is_active`, `remarks`, `title`, `url`, `article_type`, `article_id`, `parent_id`, `author`, `content`, `sort`, `module_type`) VALUES (5, '2020-02-02', '2020-02-02', 1, '', '金融行业基金：低估值的港湾', '/article/indu/aii1', 'indu', 'aii1', 'aii', '廖佳', '<p>风水总是轮流转，如果说2012年是A股市场金融行业启动的元年，那么2014年金融行业的火爆表现可谓是&ldquo;亮瞎&rdquo;了全球资本市场，行业全年上涨接近100%，与此相关的金融行业基金也因此取得了抢眼的业绩表现。</p> <p>整个A股市场经历了从2014年下半年启动的牛市后已然今非昔比，市场整体估值从13.7倍上涨至23.6倍<a href=\"file:///C:/Users/Lliao/Desktop/%E9%87%91%E8%9E%8D%E8%A1%8C%E4%B8%9A%E5%9F%BA%E9%87%91/%E6%99%A8%E6%98%9F_%E8%A1%8C%E4%B8%9A%E6%8A%A5%E5%91%8A_%E9%87%91%E8%9E%8D%E8%A1%8C%E4%B8%9A%E5%9F%BA%E9%87%91%EF%BC%9A%E4%BD%8E%E4%BC%B0%E5%80%BC%E7%9A%84%E6%B8%AF%E6%B9%BE.docx#_ftn1\" name=\"_ftnref1\" title=\"\"><!--[if !supportFootnotes]-->[1]<!--[endif]--></a>，翻了近一倍，而银行业的平均整体估值却仍在8倍以下徘徊。仅仅从估值来看，银行业仍相对处于低估值的港湾。</p> <p>而另一方面，金融改革的步伐逐步加快，银行存款保险金制度和银行资产证券化等指定相继出台，对未来银行业的发展来说既是压力也是动力。改革政策的东风之下，金融行业基金是否存在着投资机会呢?</p> <p><b>产品类型以</b><b>ETF</b><b>为主打，最近一年业绩表现抢眼</b></p> <p>目前市场上共有10只金融行业基金，从产品类型来看，其中6只为ETF，1只主动管理型基金，1只指数分级基金，另外2只为ETF联接基金。</p> <p>得益于金融行业在最近一年的出色表现，10只基金最近1年的平均总回报超过100%，排名皆处于同类前20%。其中，工银金融地产股票的回报最高，为136.25%。从最近两年、三年的业绩来看，基本均处于同类平均水平。</p> <p>与高回报形成鲜明对比的是，不论从同一时期横向的行业对比，还是该行业历史的纵向对比来看，金融保险行业的估值仍处于低洼水平，低于A股市场整体估值水平。2009年至今金融保险行业的估值一直在10倍以下，并且相对稳定。而从具体的分支行业来看，银行业的估值水平是最低的，保险、证券行业则相对偏高。进一步从这些分支行业的龙头代表公司来看，晨星股票研究的数据统计结果显示，以招商银行、工商银行、农业银行为代表的银行股的市价/公允价值<a href=\"file:///C:/Users/Lliao/Desktop/%E9%87%91%E8%9E%8D%E8%A1%8C%E4%B8%9A%E5%9F%BA%E9%87%91/%E6%99%A8%E6%98%9F_%E8%A1%8C%E4%B8%9A%E6%8A%A5%E5%91%8A_%E9%87%91%E8%9E%8D%E8%A1%8C%E4%B8%9A%E5%9F%BA%E9%87%91%EF%BC%9A%E4%BD%8E%E4%BC%B0%E5%80%BC%E7%9A%84%E6%B8%AF%E6%B9%BE.docx#_ftn2\" name=\"_ftnref2\" title=\"\"><!--[if !supportFootnotes]-->[2]<!--[endif]--></a>皆在1倍以下，中国平安、中国太保的市价/公允价值也在1倍上下。这在一定程度上说明，虽然股价在随着大势水涨船高，但相应公司的价值也在提升，而不是简单的吹估值泡沫的过程。</p> <p>&nbsp;</p>', 10, 'art_info');
INSERT INTO `fund_web`.`t_article`(`id`, `create_time`, `update_time`, `is_active`, `remarks`, `title`, `url`, `article_type`, `article_id`, `parent_id`, `author`, `content`, `sort`, `module_type`) VALUES (6, '2020-02-02', '2020-02-02', 1, '', '国内公募量化基金纵览——发展历程、产品线布局及团队配置', '/article/indu/aii2', 'indu', 'aii2', 'aii', '姜鹏', '<p>去年是国内量化产品集中爆发的一年，延续2013年的良好势头，阳光私募量化基金全年共成立超过140只。公募方面，虽然发行的绝对数目与私募相比突破不大，但量化基金自去年2季度开始受到投资者关注，之后不乏单季度扩容5倍以上的热门产品，量化投资的春天仿若瞬间来临。</p> <p>2014年度业绩来看，晨星股票型量化基金中有近7成的基金回报率排在股票型基金前半区，多只量化基金入围同类前10%。相信随着这类产品数量增多，未来投资者将看到更多量化基金载入年度榜单前列。</p> <p>值此之际，通过回顾国内公募量化基金的发展历程，纵观其产品线的类型布局，进而统计基金公司量化产品线的市场份额及投资团队构成，希望为投资者提供该细分领域的信息和筛选量化基金的初步视角。<span lang=\"EN-US\" style=\"font-family: \'Morningstar 1\', sans-serif;\" /></p>', 20, 'art_info');
INSERT INTO `fund_web`.`t_article`(`id`, `create_time`, `update_time`, `is_active`, `remarks`, `title`, `url`, `article_type`, `article_id`, `parent_id`, `author`, `content`, `sort`, `module_type`) VALUES (7, '2020-02-03', '2020-02-03', 1, '', '新基金观察（201907）：纯债、股票型基金为新发主力军 汇添富吸金能力抢眼', '/article/survey/ais3', 'survey', 'ais3', 'ais', '李玉渊', '<p><b>产品动态回顾</b></p> <p>7月，按摊余成本法估值的债券基金相继入市，有望承接货币基金转型为市值型货币基金所溢出的资金，定期开放式债券基金在此方面或有更为突出的优势。首先，定开债基的流动性管理较容易控制，在其封闭运作的期间不易被新申购资金摊薄收益。其次，定开债基的杠杆上限为200%，较140%上限的开放式基金更为灵活。据证券时报报道，目前摊余成本法债券基金多为机构定制产品，且可能按照客户要求限额发售。因此，个人投资者可选的此类产品仍有限。</p> <p>ETF基金仍为市场关注的焦点。产品创新方面，据证券时报报道，7月26日，国内首批国企一带一路ETF及其联接基金、首批央企创新ETF及其联接基金获批。此类基金的跟踪标的为国企一带一路指数，或将有助于优化央企股份配置，强化央企市值管理能力，促进国有资本合理流动，实现国有资本保值增值。次新基金方面，上海证券报道，二季度指数基金规模仍大幅增长，且有较为突出的 &ldquo;强者恒强&rdquo; 的头部效应。二季度新发基金中，主题及债券指数型基金吸金能力较强。</p> <p>另外，市场较为关注前7月新发基金的趋势。据证券时报报道，产品布局方面，大型公司有加速布局新产品的趋势，而中、小型基金公司却速度放缓。发行规模方面，行业整体呈现&ldquo;马太效应&rdquo;。其中，汇添富吸金能力最为突出，共募集资金355.66亿元。发行品类方面，债券基金和指数型基金最受投资者热捧。</p> <p><b>市场概述：纯债型和股票型基金为新发主力军</b></p> <p>7月，市场上共有44家基金公司发行基金，基金发行总数合计52只。其中，按投资组合统计，纯债型基金和股票型发行量最大，发行只数分别为21只和10只。而其它各类基金发行数量均未超过5只。在本月新发基金中，10只基金为被动管理基金，且股票型基金仍为被动管理基金的主要发行类别。</p> <p>募集规模方面，市场上已有11只基金披露了募集规模数据，合计募集规模为75.49亿元。其中，10只基金已在7月结束了募集期。但是，本月市场上最为吸金的基金并非纯债型或股票型基金，而是沪港深股票型基金。具体来看，这一类别基金中仅汇添富内需增长股票发行成立，募集规模为40.13亿，延续了上半年大型基金公司产品募资能力凸显的特征。此外，投资者目前并未展现出更青睐被动型基金产品的意向，被动型基金募集规模共7.18亿元，占总募集规模的10%。具体来看，7月有募集数据的2只指数型基金的募集规模呈分化行情。浦银安盛上海清算所高等级优选短期融资券指数A以5.5亿的募集规模排名第三，而永赢沪深300指数A募集规模则为1.68亿，募集规模较小。</p>', 30, 'art_info');


