# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_dict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=1)),
                ('remarks', models.CharField(default='', max_length=50)),
                ('type', models.CharField(db_index=True, max_length=20, verbose_name='类型')),
                ('valid', models.IntegerField(db_index=True, max_length=20, verbose_name='Key')),
                ('value', models.CharField(max_length=32, verbose_name='Value')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('create_user', models.CharField(default=None, max_length=32, verbose_name='类型')),
            ],
            options={
                'verbose_name': '项目字典',
                'db_table': 'system_dict',
            },
        ),
    ]
