# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-29 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title_url_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=1)),
                ('remarks', models.CharField(blank=True, default='', max_length=50)),
                ('url', models.CharField(default='', max_length=80, verbose_name='路径')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('type', models.CharField(db_index=True, max_length=20, verbose_name='类型')),
                ('sort', models.IntegerField(default=0, verbose_name='value')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父标题id')),
            ],
            options={
                'verbose_name': '标题路径对应表',
                'verbose_name_plural': '标题路径对应表',
                'db_table': 't_title_url',
            },
        ),
        migrations.AlterModelOptions(
            name='project_dict',
            options={'verbose_name': '项目字典', 'verbose_name_plural': '项目字典'},
        ),
        migrations.AlterField(
            model_name='project_dict',
            name='create_user',
            field=models.CharField(blank=True, default=None, max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='project_dict',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
