# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-01-31 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200129_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_dict',
            name='valid',
            field=models.IntegerField(db_index=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='title_url_model',
            name='sort',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
