# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-02-27 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200131_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sync_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=20, unique=True, verbose_name='所属模块')),
                ('prefix', models.CharField(max_length=20, verbose_name='前缀')),
                ('serial_num', models.IntegerField(default='100000', verbose_name='auto编号')),
            ],
            options={
                'verbose_name': '标题路径对应表',
                'verbose_name_plural': '标题路径对应表',
                'db_table': 't_sync_code',
            },
        ),
    ]
