# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-04 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_sync_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sync_code',
            options={'verbose_name': '序列号管理', 'verbose_name_plural': '序列号管理'},
        ),
    ]
