# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-05 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200304_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_dict',
            options={'ordering': ('type', 'sort'), 'verbose_name': '项目字典', 'verbose_name_plural': '项目字典'},
        ),
    ]
