# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-06 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20200305_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_dict',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project_dict',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='title_url_model',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='title_url_model',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
