# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-13 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200307_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='title_url_model',
            name='module',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='所属模块'),
        ),
    ]
