# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-07-15 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_title_url_model_module'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title_url_model',
            options={'ordering': ('parent_id', 'sort'), 'verbose_name': '标题路径对应表', 'verbose_name_plural': '标题路径对应表'},
        ),
    ]
